### ISSUE TITLE
TS2304: Cannot find name 'object'

### ISSUE THREAD

**Issue by JorgeLGonzalez** [dphilipson/typescript-string-enums#17]
I just installed this package as it seems to do exactly what I need, but typescript complains with TS2304: Cannot find name 'object' on line 7 of index.d.ts, which presumably corresponds to https://github.com/dphilipson/typescript-string-enums/blob/master/src/index.ts#L18. 

I simply changed object to Object as a workaround. Any reason that is object (lowercase "o")? 
`export declare type Enum<T extends object> = T[keyof T];`

**Comment by dphilipson** [comment]
Hi Jorge,

That error means you're on a pre-2.2 version of TypeScript. `object` is a new type added in 2.2 as described in the [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html) and specifies a nonprimitive type, by contrast to `Object` which is the interface containing methods such as `hasOwnProperty`, `toString`, etc. The code uses `object` to make the following incorrect usages show as type errors:
``` javascript
type BadEnum1 = Enum<2>;
type BadEnum2 = Enum<"hello">;
type BadEnum3 = Enum<null>;
```
Is upgrading a problem for you? My hope was that since the library needs TypeScript 2.1 to work at all, it would be okay to require a recent version (2.1 is when mapped and index types were introduced, which this library depends on). Do developers need compatibility with 2.1 <= TS version < 2.2? I'll leave this issue open for a while so people can chip in if they need 2.1 support.

If you need 2.1 compatibility right now and can't upgrade, you can use version 0.2.0 of this library instead.

**Comment by dphilipson** [comment]
Added a note to the README listing the version requirements.

**Comment by JorgeLGonzalez** [comment]
David,

Thanks so much for the speedy and informative reply! I'll give downgrading a shot. (Need to keep our project's TypeScript version in lockstep with the Angular version (currently at 2.1.6 in ng 4). I'm sure we'll upgrade TS in the next few months so I would not worry about trying to maintain compatibility with 2.1.x.

Cheers,
Jorge
