### ISSUE TITLE
enums in ngSwitch

### ISSUE THREAD

**Issue by joe307bad** [dphilipson/typescript-string-enums#20]
I was not able to use ngSwitch using this enum method as the ngSwitch expression.

**Comment by dphilipson** [comment]
Hi Joe, I've never used Angular but here's what I was able to find looking around online. First, the reason it's not working is because `ngSwitch` only works with primitive values, not expressions:

> Be aware that the attribute values to match against cannot be expressions. They are interpreted as literal string values to match against. For example, `ng-switch-when="someVal"` will match against the string `"someVal"` not against the value of the expression `$scope.someVal`.

[Source](https://docs.angularjs.org/api/ng/directive/ngSwitch)

The main workaround that I see suggested is to use `ngIf` instead (e.g. `ng-if="key === MyEnum.value"`, where both `key` and `MyEnum` are put in scope). Also, there's an interesting workaround suggested in [this Stack Overflow answer](http://stackoverflow.com/a/33399030/2695248) involving creating a custom directive which acts like `ngWhen` but evaluates its argument as an expression.

Does that solve the problem? Are there any Angular users around who can chime in?

**Comment by dphilipson** [comment]
Hihi!

I'm going to close this in a few days if I don't hear a response. Let me know if you have other thoughts.
