### ISSUE TITLE
Refactor/rename support

### ISSUE THREAD

**Issue by jkillian** [dphilipson/typescript-string-enums#6]
Hey @dphilipson, we're enjoying using your library! The biggest issue I've found is that I can't figure out a good way to rename fields in my project, and manually searching / changing things isn't as nice. Do you know if there's a way to do renames automatically?

**Comment by dphilipson** [comment]
Hi @JKillian,

In my projects, I've always just done a project-wide find/replace (e.g. "ServerStatus.RUNNING" -> "ServerStatus.STARTED"), which works well enough because the enum type (`ServerStatus` here) acts as a namespace to prevent the wrong things from getting caught up. Of course, that breaks if you happen to have the string "ServerStatus.RUNNING" somewhere in your project not referring to the enum, but I feel like that would be a rare scenario and I've never encountered it.

If you really want to safeguard against that case and still avoid manual replacements, you could first use an IDE to rename "ServerStatus" to "ServerStatus_TEMP", then do a project-wide find/replace of "ServerStatus_TEMP.RUNNING" -> "ServerStatus_TEMP.STARTED", then use your IDE to rename "ServerStatus_TEMP" back to "ServerStatus".

Maybe this isn't quite what you wanted, but I've personally found it to be an acceptable solution.

**Comment by jkillian** [comment]
Thanks @dphilipson! I think you address this issue well above, and don't think there's really any actionable steps for a better solution so going to close this issue. It's fair to say it's a TypeScript limitation, but even the extent to which they could automatically refactor things is unclear.
